import { Room, Tour } from '@/types'

export const roomsData: Room[] = [
  {
    id: 1,
    name: 'Deluxe Ocean View',
    description: 'Wake up to stunning ocean views from your private balcony. This spacious room features a king-size bed, modern amenities, and elegant decor.',
    price: 299,
    size: '450',
    beds: '1 King Bed',
    maxGuests: 2,
    amenities: ['wifi', 'breakfast', 'parking', 'beach'],
    images: ['room1-1.jpg', 'room1-2.jpg', 'room1-3.jpg'],
  },
  {
    id: 2,
    name: 'Premium Suite',
    description: 'Luxury living at its finest. Separate living area, jacuzzi tub, and premium bedding for the ultimate comfort experience.',
    price: 459,
    size: '750',
    beds: '1 King Bed + Sofa Bed',
    maxGuests: 4,
    amenities: ['wifi', 'breakfast', 'parking', 'gym', 'pool'],
    images: ['room2-1.jpg', 'room2-2.jpg', 'room2-3.jpg'],
  },
  {
    id: 3,
    name: 'Garden View Double',
    description: 'Peaceful garden views with two comfortable double beds. Perfect for friends or family traveling together.',
    price: 199,
    size: '350',
    beds: '2 Double Beds',
    maxGuests: 4,
    amenities: ['wifi', 'breakfast', 'parking'],
    images: ['room3-1.jpg', 'room3-2.jpg', 'room3-3.jpg'],
  },
  {
    id: 4,
    name: 'Executive King Room',
    description: 'Business-friendly room with dedicated workspace, high-speed internet, and premium amenities for the working traveler.',
    price: 279,
    size: '400',
    beds: '1 King Bed',
    maxGuests: 2,
    amenities: ['wifi', 'breakfast', 'parking', 'gym'],
    images: ['room4-1.jpg', 'room4-2.jpg', 'room4-3.jpg'],
  },
  {
    id: 5,
    name: 'Family Suite',
    description: 'Spacious suite with separate bedroom for parents and bunk beds for kids. Family-friendly amenities included.',
    price: 389,
    size: '600',
    beds: '1 Queen Bed + 2 Bunk Beds',
    maxGuests: 6,
    amenities: ['wifi', 'breakfast', 'parking', 'pool'],
    images: ['room5-1.jpg', 'room5-2.jpg', 'room5-3.jpg'],
  },
  {
    id: 6,
    name: 'Honeymoon Suite',
    description: 'Romantic retreat with champagne on arrival, flower petals, and private terrace with sunset views.',
    price: 599,
    size: '800',
    beds: '1 King Bed',
    maxGuests: 2,
    amenities: ['wifi', 'breakfast', 'parking', 'beach', 'pool'],
    images: ['room6-1.jpg', 'room6-2.jpg', 'room6-3.jpg'],
  },
]

export const toursData: Tour[] = [
  {
    id: 1,
    name: 'Sunset Coastal Hike',
    description: 'Experience breathtaking coastal views as we hike along scenic trails ending with a spectacular sunset view.',
    price: 75,
    duration: '3 hours',
    maxParticipants: 12,
    location: 'Coastal Trail',
    highlights: [
      'Expert local guide',
      'Scenic photography spots',
      'Light refreshments',
      'Wildlife spotting',
    ],
    images: ['tour1-1.jpg', 'tour1-2.jpg', 'tour1-3.jpg'],
  },
  {
    id: 2,
    name: 'Wine Tasting Tour',
    description: 'Visit local vineyards and taste award-winning wines while learning about regional winemaking traditions.',
    price: 120,
    duration: '5 hours',
    maxParticipants: 8,
    location: 'Local Vineyards',
    highlights: [
      'Visit 3 wineries',
      'Wine tasting sessions',
      'Gourmet cheese pairing',
      'Transportation included',
    ],
    images: ['tour2-1.jpg', 'tour2-2.jpg', 'tour2-3.jpg'],
  },
  {
    id: 3,
    name: 'Kayaking Adventure',
    description: 'Paddle through serene waters and explore hidden coves and marine life with our expert guides.',
    price: 65,
    duration: '2.5 hours',
    maxParticipants: 6,
    location: 'Protected Bay',
    highlights: [
      'All equipment provided',
      'Safety briefing',
      'Wildlife observation',
      'Beginner-friendly',
    ],
    images: ['tour3-1.jpg', 'tour3-2.jpg', 'tour3-3.jpg'],
  },
  {
    id: 4,
    name: 'Cultural Village Tour',
    description: 'Immerse yourself in local culture with visits to traditional villages, crafts, and authentic cuisine.',
    price: 90,
    duration: '4 hours',
    maxParticipants: 15,
    location: 'Cultural Sites',
    highlights: [
      'Traditional craft demonstrations',
      'Local lunch included',
      'Cultural performances',
      'Historic site visits',
    ],
    images: ['tour4-1.jpg', 'tour4-2.jpg', 'tour4-3.jpg'],
  },
  {
    id: 5,
    name: 'Stargazing Experience',
    description: 'Away from city lights, enjoy crystal-clear night skies with telescope viewing and astronomy guidance.',
    price: 55,
    duration: '2 hours',
    maxParticipants: 10,
    location: 'Observatory Hill',
    highlights: [
      'Professional telescope',
      'Astronomy guide',
      'Hot beverages',
      'Star charts provided',
    ],
    images: ['tour5-1.jpg', 'tour5-2.jpg', 'tour5-3.jpg'],
  },
  {
    id: 6,
    name: 'Mountain Biking Trail',
    description: 'Challenge yourself on our guided mountain biking trails through forests and hills with varying difficulty levels.',
    price: 85,
    duration: '3.5 hours',
    maxParticipants: 8,
    location: 'Mountain Trails',
    highlights: [
      'Bike and helmet rental',
      'Trail guidance',
      'Safety equipment',
      'Difficulty options',
    ],
    images: ['tour6-1.jpg', 'tour6-2.jpg', 'tour6-3.jpg'],
  },
]